apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: music-app
  template:
    metadata:
      labels:
        app: music-app
    spec:
      containers:
      - name: music-player
        image: sunil6680/project-cicd:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: impulse-app-svc
spec:
  selector:
    app: music-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer    
   

